version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "daily"
    target_branch: "dependencies"
    commit_message:
      prefix: "chore"
      include_scope: true

