name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    container: switchbitcom/winch:golang
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: git config --global url."https://$GITHUB_TOKEN:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/cache@v1
        with:
          path: /go/pkg/mod
          key: v1-go-mod-${{ hashFiles('go.sum') }}
          restore-keys: v1-go-mod-

      - run: winch ci
